### ISSUE TITLE
SmartSyncExplorerReactNative throws redbox on scrolling

### ISSUE THREAD

**Issue by ErnstEeldert** [forcedotcom/SalesforceMobileSDK-Templates#184] opened 2019-02-13 20:21 UTC
I just tried the SmartSyncExplorerReactNative sample app. It works fine, but throws a redbox when scrolling down the list of contacts (the org I am connecting to has over 10K contacts).

Doing some digging in the code, it looks like the cursor object passed in to smartstore.moveCursorToPageIndex doesn't get deserialized properly, resulting into a 101th element in the accumulatedResults array with an undefined value.

To repro, follow these steps:

1. Connect to an org with more than pagesize (=100?) contacts.
2. Scroll down the list to the last item.
3. RN throws the following error:

![simulator screen shot - iphone 6 - 2019-02-13 at 21 08 15](https://user-images.githubusercontent.com/8919203/52741322-5d37fa80-2fd5-11e9-96cb-527c636af42f.png)

**Comment by wmathurin** [comment] 2019-02-21 01:35
An easier way to hit the bug is to change the page size in `searchContacts` in  `StoreMgr.js`.
For instance by doing:
```javascript
        querySpec = smartstore.buildAllQuerySpec("LastName", "ascending", 5);
```
Instead of 
```javascript
        querySpec = smartstore.buildAllQuerySpec("LastName", "ascending", 100);
```

**Comment by wmathurin** [comment] 2019-02-21 01:36
It's a regression. `moveCursorToPageIndex` broke in 7.0.
Thanks for reporting the issue. The problem is fixed in dev, see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/113.
It will be in our next release Mobile SDK 7.1.
In the mean time, you can just point your package.json to the dev version of react.native.force:
```json
"react-native-force": "https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#dev",
```

**Closed by wmathurin** 2019-02-21 01:36 UTC
